import Navbar from "@/components/shared/Navbar";
import Sidebar from "@/components/shared/Sidebar";
import { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import React from "react";

export const metadata: Metadata = {
  title: "CampusFlow_Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en">
        <body>
          <div className=" h-screen  flex">
            <div className="right w-5/6 md:w-[92%] lg:w-5/6 xl:w-[86%] bg-[#F7F8FA] overflow-scroll">
              <Navbar />
              {children}
            </div>
            <div className="left w-1/6 md:w-[8%] lg:w-1/6 xl:w-[14%]  p-0 border-l-2">
              <Link
                href={"/"}
                className=" flex items-center justify-center lg:justify-start gap-2"
              >
                <Image src={"/vercel.svg"} alt="Logo" height={32} width={32} />
                <span className="hidden md:block lg:block">CampusFlow</span>
              </Link>
              <Sidebar />
            </div>

            {/* {children} */}
          </div>
        </body>
      </html>
    </>
  );
}
